version: '3.8'

services:
  web:
    build: ./
    container_name: flask
    restart: always
    expose: 
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
    entrypoint: ./entrypoint.sh
  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=flasky
      - POSTGRES_PASSWORD=flask1234
      - POSTGRES_DB=flask
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8008:80"

volumes:
  postgres_data:
