"""ML item unique nickname removed

Revision ID: 7287dc6fd14d
Revises: 209a1509c044
Create Date: 2022-06-26 21:19:38.016562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7287dc6fd14d'
down_revision = '209a1509c044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_nickname', table_name='item')
    op.create_index(op.f('ix_item_nickname'), 'item', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_nickname'), table_name='item')
    op.create_index('ix_item_nickname', 'item', ['nickname'], unique=False)
    # ### end Alembic commands ###
